name: Deploy GitHub pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deplot:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          publish_dir: ./
          github_token: ${{ secrets.GITHUB_TOKEN }}
